name: Poll YouTube for Live Streams

on:
  schedule:
    - cron: '55 8-20 * * *'  # At 55 minutes past every hour from 8am to 8pm
    - cron: '10 9-21 * * *'  # At 10 minutes past every hour from 9am to 9pm
    - cron: '25 8-20 * * *'  # At 25 minutes past every hour from 8am to 8pm
    - cron: '40 8-20 * * *'  # At 40 minutes past every hour from 8am to 8pm
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  pull-requests: none
  actions: write

jobs:
  poll-youtube:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib
    
    - name: Create data directory
      run: mkdir -p data
    
    - name: Update streams data
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: python script/update_streams.py
    
    - name: Check if streams.json changed
      id: check_changes
      run: |
        git add data/streams.json
        if ! git diff --cached --quiet; then
          echo "changed=true" >> "$GITHUB_OUTPUT"
        fi

    - name: Commit and push if changed
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Update streams data"
        git push

    - name: Trigger deploy workflow
      if: steps.check_changes.outputs.changed == 'true'
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'deploy.yml',
            ref: 'main'
          })
