name: YouTube playlist polling
on:
  schedule:
    - cron: '5/10 * * * *'
on: [push]
jobs:
  find-videos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip poetry
          poetry install
      - name: Test Poetry environment
        run: |
          poetry run python --version