name: Poll YouTube for Live Streams

on:
  schedule:
    - cron: '55 8-20 * * *'  # At 55 minutes past every hour from 8am to 8pm
    - cron: '10 9-21 * * *'  # At 10 minutes past every hour from 9am to 9pm
    - cron: '25 8-20 * * *'  # At 25 minutes past every hour from 8am to 8pm
    - cron: '40 8-20 * * *'  # At 40 minutes past every hour from 8am to 8pm
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: none

jobs:
  poll-youtube:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib
    
    - name: Create data directory
      run: mkdir -p data
    
    - name: Update streams data
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: python script/update_streams.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data/streams.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update streams data" && git push)
