name: Test Scripts

on:
  push:
    paths:
      - 'script/**'
  pull_request:
    paths:
      - 'script/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          
      - name: Install dependencies
        run: |
          uv sync --group test
          
      - name: Run tests
        run: |
          uv run pytest script/tests -v 