name: Test Scripts

on:
  push:
    paths:
      - 'script/**'
  pull_request:
    paths:
      - 'script/**'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
        BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        SKIP_BLUESKY_POSTING: "true"
    steps:
      - uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
          
      - name: Install dependencies
        run: |
          uv sync --group test
          
      - name: Run tests
        run: |
          uv run pytest script/tests -v 